#!/bin/bash
quote='"'
query=$quote$*$quote
data1='response newSimpleExcel().writeToSheet("Sheet1",(hsql.executeQuery('
data2='))).toDataSource()'
data=$data1$query$data2
curl -o gripresult.xls -data="$data" localhost:5050/exec